### ISSUE TITLE
A new version

### ISSUE THREAD

**Issue by houd1ni** [dimitrinicolas/marmottajax#18]
Hi, Dimitry!

I'm thinking of making a version with very different API (we can discuss it in gitter), based on half of year heavy (and high-load) usage of the Library.

It'd be faster, several times more rubust and conveinent, and, also almost the same size.

One of the main innovation would be modularity and first module is socket.io adapter.

How do you feel with it? I guess, it would be better to name it like Marmott 2 or so. If you want, you can create a new repository, or I can make my own, if you feel OK that I'll point new users to that repo. Anyway, you'll be contributor from the very beginnig.

**Comment by dimitrinicolas** [comment]
Hi !

I'm currently on long vacancy, so I can't decide now, do as you want 😉

**Comment by houd1ni** [comment]
@dimitrinicolas  ok!) I'll make own repository and link them.

**Comment by houd1ni** [comment]
Here it is! https://github.com/houd1ni/Marmott2
