### ISSUE TITLE
Small issue with setting the json paramater

### ISSUE THREAD

**Issue by tehmedicineman** [dimitrinicolas/marmottajax#22]
The examples show using a boolean to set the json parameter, but the code types it as a "string" instead of a "boolean".

So when you go to run a call you need to set it as "json:'true'" instead of "json:true" or else it won't work.

The typemap needs to be updated to make "json" type to "boolean", unless its intentional to have to set it as a string saying "true", if thats the case then the examples/documentation would be the place that needs to get updated.

**Comment by dimitrinicolas** [comment]
I don't understand your issue, in the example the parameter "json: true" work perfectly and in the source code, the function only check ["if (this.json)"](https://github.com/dimitrinicolas/marmottajax/blob/master/bin/marmottajax.js#L347)

I don't understand why "true" must be a string
