### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by Rudolph-Miller** [dimitrinicolas/marmottajax#3]
Please publish this package to npm.

**Comment by dimitrinicolas** [comment]
I will first improve the code, then I would publish this on npm :wink:

**Comment by Rudolph-Miller** [comment]
thx

**Comment by Rudolph-Miller** [comment]
:clap:

**Comment by dimitrinicolas** [comment]
I don't understand, why do you want this librairy on npm ?
I don't know how bower or other things like this works... :cry:

**Comment by dimitrinicolas** [comment]
I've just published it to https://www.npmjs.com/package/marmottajax but there is no `module.exports`.
I don't know how do you want do use this package, if there is any issue, tell me :wink:

**Comment by Rudolph-Miller** [comment]
Cuz just my products are on npm.
If this is on npm, I can `require` like CommonJS style this library with dependency in `package.json`.
Bower has almost the same method to npm.
You can publish in bower to put bower.json and `bower register`.

**Comment by dimitrinicolas** [comment]
Ah thank you !

And CommonJs an require package without module.exports ?

**Comment by Rudolph-Miller** [comment]
I see. It seems I can not `require` the library.
You just concatenating with gulp.
You should create a file which will be required by gulp and `export` some objects or functions, and add `main` section to package.json to specify which file is main for package.json.

**Comment by dimitrinicolas** [comment]
Yep, I will do that asap ; )

Le jeu. 26 févr. 2015 à 19:34, Rudolph Miller <notifications@github.com> a
écrit :
