### ISSUE TITLE
Use english + optional i18n

### ISSUE THREAD

**Issue by lamuertepeluda** [dimitrinicolas/marmottajax#4]
Hi guys I love french but plz use English as standard conventional language for comments and error message (and computer-stuff in general). This will help you getting feedbacks and collaboration.
You may add internationalization with a i18n library as optional.

**Comment by dimitrinicolas** [comment]
Thank you for the recommendation, I am currently on vacation, I would do that as soon as possible :wink:

**Comment by dimitrinicolas** [comment]
voilà :grin:
